### ISSUE TITLE
ToDo to version 1.0

### ISSUE THREAD

**Issue by otoyo** [otoyo/easy-notion-blog#123]
# v0.13

- [x] Support ToDo blocks https://github.com/otoyo/easy-notion-blog/pull/128
- [x] Support "Table of Contents" blocks https://github.com/otoyo/easy-notion-blog/pull/130
- [x] Add more tests https://github.com/otoyo/easy-notion-blog/pull/131
- [x] Define API Response interfaces https://github.com/otoyo/easy-notion-blog/pull/132
- [x] Delete useless files https://github.com/otoyo/easy-notion-blog/pull/133

# 1.0.0

- Support Semantic Versioning
- Update Next.js to 13
